name: Run tests

on:
  push:
  pull_request:

jobs:
  run-tests-ce:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'pull_request' && github.event.pull_request.head.repo.owner.login != 'tarantool'
    strategy:
      matrix:
        tarantool-version: ["1.10", "2.8"]
      fail-fast: false
    runs-on: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: ${{ matrix.tarantool-version }}

      - name: Install dependencies
        shell: bash
        run: ./deps.sh

      - name: Build
        run: tarantoolctl rocks make

      - name: Run linter
        run: .rocks/bin/luacheck .

      - name: Run tests
        run: |
          rm -f tmp/luacov*
          .rocks/bin/luatest --verbose --coverage --shuffle group
          .rocks/bin/luacov . && grep -A999 '^Summary' tmp/luacov.report.out
